version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    # Приложение будет доступно только для Caddy (обратного прокси) внутри сети docker-compose

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  postgres_data:
  caddy_data:     # Данные Caddy (в том числе SSL-сертификаты от Let's Encrypt)
  caddy_config:
